name = "§lNEWB x UNWIND 5.0"
version = [0, 16, 0]
min_supported_mc_version = [1, 21, 111]
description = '''
§c%w
§7- An enchanced vanilla shader for Minecraft!
%v
§3https://devendrn.github.io/newb-shader/
''' # %w = patch warning, %v = version
authors = ["Hazelntz", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "f8628f6a-3f81-4c59-8c6a-2a55172518d1" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]

[info] 
copyright = '''
Copyright © 2025 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
No Wave 
'''

[[subpack]]
define = "ROUNDED_CLOUDS"
materials = ["Clouds"]
description = '''
Rounded Clouds
'''

[[subpack]]
define = "VOLUMETRIC_CLOUDS"
materials = ["Clouds"]
description = '''
Volumetric Clouds
'''

[[subpack]]
define = "VANILLA_CLOUDS"
materials = ["Clouds"]
description = '''
Vanilla Clouds
'''

#[[subpack]]
#define = "LITE"
#materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]
#description = '''
#Many effects disabled. A bit lighter!
#'''